# Base Hyprland config for wkstation
# Core behavior lives here.
# Theme-specific visuals are loaded from theme.conf

source = ~/.config/hypr/theme.conf

monitor=,preferred,auto,auto

exec-once = waybar
exec-once = hyprpaper
exec-once = hypridle
exec-once = blueman-applet

input {
    kb_layout = us
}

general {
    allow_tearing = false
}

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
}

bind = SUPER, RETURN, exec, foot
bind = SUPER, SPACE, exec, rofi -show drun -show-icons
bind = SUPER, Q, killactive
bind = SUPER, F, togglefloating
bind = SUPER SHIFT, E, exit
