general {
    gaps_in = 12
    gaps_out = 18
    border_size = 2
    col.active_border = rgba(00ffeaff)
    col.inactive_border = rgba(222222ff)
}

decoration {
    rounding = 12

    shadow {
        enabled = false
    }
}
